[versions]
libraryGroup = "com.github.pedroSG94"
versionCode = "250"
versionName = "2.5.0"

#plugins versions
agp = "8.5.2"
kotlin = "2.0.20"
dokka = "1.9.20"

#dependencies versions
#noinspection GradleDependency, version 1.7.0 need min sdk 21
appcompat = "1.6.1"
constraintlayout = "2.1.4"
camerax = "1.3.4"
multidex = "2.0.1"
annotation = "1.8.2"
coroutines = "1.8.1"
junit = "4.13.2"
mockito = "5.4.0"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "maven-publish", version.ref = "agp" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

[bundles]
androidx-camera = ["androidx-camera-core", "androidx-camera-camera2", "androidx-camera-lifecycle"]